### ISSUE TITLE
LDAP+fmDNS

### ISSUE THREAD

**Issue by kostjan285** [WillyXJ/facileManager#342]
Hi.
need help in the implementation of LDAP authentication .
AD user assigns the user password DN

Sorry , I use google.translate.com

**Comment by WillyXJ** [comment]
Hi. To configure LDAP, select "LDAP Authentication" method, enter your LDAP server (and ports if different from the default), protocol version, encryption (if applicable), referrals (if applicable), the DN (using the examples as a template leaving <username> as fM will replace <username> with the authenticating user), any group membership requirements, and a user template to base the LDAP users off of.  From the help file:

> **LDAP Authentication**
> Users are authenticated against a defined LDAP server. Upon success, users are created in the facileManager database using the selected template account for granular permissions within the environment. If no template is selected then user authentication will fail (this is another method of controlling access to facileManager). 

I hope this helps.

**Comment by kostjan285** [comment]
the problem in the code, try to set up and you will see

**Comment by WillyXJ** [comment]
There are two ways of limiting which LDAP users can login:

1. Set the Group Attribute to the DN of the group the users must be a part of
2. Add the LDAP users within fM and don't use a login template

**Comment by kostjan285** [comment]
In this way I do not work
**Group Distinguished Name (DN)**
CN = OALG FMDNS Users, OU = Other Access List Groups, OU = Domain Groups, DC = domen, DC = com
**Group Member Attribute**
what to enter?

**Comment by kostjan285** [comment]
![ldap](https://cloud.githubusercontent.com/assets/21363721/18166933/a67f0062-7056-11e6-867c-2c130bb3609c.JPG)

**Comment by WillyXJ** [comment]
I see you are using AD and I have found in my tests today that LDAP authentication with the group membership requirement works with LDAP, but not AD.  Until a fix is released, please disable the group membership requirement with AD.

Thank you for bringing this to my attention.

**Comment by kostjan285** [comment]
Thank you, we will wait

**Comment by WillyXJ** [comment]
This will be included in [3.0-alpha2](http://www.facilemanager.com/download/?t=4) and later.

**Comment by kostjan285** [comment]
I updated, but still does not allow a group of users to login :(

**Comment by kostjan285** [comment]
that he does not like?
[Tue Oct 18 12:25:54.648495 2016] [:error] [pid 10586] [client ip-address:port] PHP Warning:  ldap_search(): Search: Operations error in /var/www/html/facileManager/server/fm-modules/facileManager/classes/class_logins.php on line 650
, referer: http://ip-address/facileManager/server/
    code :     "(samaccountname={$samaccountname})", $attributes);

**Comment by WillyXJ** [comment]
What values are you using in the Group Membership settings? It's possible you need to adjust your attribute based on your environment. Using "memberof" is what I needed in my test environment.

**Comment by kostjan285** [comment]
Group Distinguished Name (DN)  CN=OALG FMDNS Users,OU=Other Access List Groups,OU=Domain Groups,DC=domain,DC=corp

**Comment by WillyXJ** [comment]
Without seeing your AD environment, I'm just guessing here, but you probably need to use "memberof" for your attribute.
