### ISSUE TITLE
[BUG] fmdns import zone records Append Domain problem

### ISSUE THREAD

**Issue by marksmansj** [WillyXJ/facileManager#486]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.5.7**
{fmDNS} Version : **3.4.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

**(BUG | ISSUE) Actual Behavior:**

**(BUG | ISSUE) Steps to reproduce:**

{
first my domain name is pic.liz.com and I used a cdn service . they(cdn) provided me a CNAME is pic.liz.com.wswebpic.com.  this record(pic.liz.com. CNAME pic.liz.com.wswebpic.com. ) was setting in my old bind dns. when I dumped this zone and imported it into fmdns. I found this record value turned into "picwswebpic.com." .  as if the ".liz.com." in the cname value is removed by 'no' for append domain.
}

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 4.0-beta1](http://www.facilemanager.com/modules/fmdns/?t=3) and later. Final release will come out later.

**Comment by WillyXJ** [comment]
[fmDNS 4.0.0](http://www.facilemanager.com/modules/fmdns/) has been released.

**Comment by marksmansj** [comment]
facileManager v4.0.0
fmDNS v4.0.0

php -v
PHP 7.2.31 (cli) (built: May 12 2020 10:09:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.31, Copyright (c) 1999-2018, by Zend Technologies

cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)

when I import my zone into fmdns 4.0 . the problem is still exist.

**Comment by WillyXJ** [comment]
That's interesting. Here is my test data in a text file that I imported:

```
pix.test-domain.local. IN CNAME pix.test-domain.local.wspics.com.
pix3.test-domain.local. IN CNAME pix
pix2.test-domain.local. IN CNAME pix3.test-domain.local.
```
And here is how it imported:

<img width="836" alt="Screen Shot 2020-11-13 at 7 46 34 AM" src="https://user-images.githubusercontent.com/1309591/99084709-890a5a80-2584-11eb-91ac-60ab0d6a3580.png">

Have I misunderstood the request and your example?

**Comment by marksmansj** [comment]
![QQ图片20201123124206](https://user-images.githubusercontent.com/50012913/99929902-0a829980-2d8a-11eb-9acb-e05c95c40b83.png)

![QQ图片20201123124515](https://user-images.githubusercontent.com/50012913/99929969-4a498100-2d8a-11eb-9357-3e959d2d7ad2.png)
I figured out while I uploaded the dump file at "File To Import" and do not choose Zone at "Zone To Import To" ,  it will appear this problem. if I choose the Zone at "Zone To Import To" , it's ok.

**Comment by WillyXJ** [comment]
Thanks for the extra information as I've been able to reproduce this with the bulk import wizard.

**Comment by marksmansj** [comment]
> Thanks for the extra information as I've been able to reproduce this with the bulk import wizard.

thank you so much

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 4.0.1](http://www.facilemanager.com/modules/fmdns/) and later.

**Comment by marksmansj** [comment]
> This is now fixed in [fmDNS 4.0.1](http://www.facilemanager.com/modules/fmdns/) and later.

I tested it with fmDNS 4.0.1 . It's Ok now. and hope can support regular expression of search function at future version. thank you so much
![1RD (LKQ}XM}@4 7$QP1_XD](https://user-images.githubusercontent.com/50012913/100693125-2f4cc180-33c7-11eb-8085-2bdfcd0e4616.png)
